"""End-to-end CLI tests for ``vaultspec-core vault feature rename``.

Drives the real Typer command through the :class:`WorkspaceFactory` runner
against a real installed workspace and a real, schema-valid feature corpus.
Asserts the human output, a clean ``vault check all`` afterwards, the
versioned JSON envelope, and the collision-without-force failure envelope.

No test doubles: every document is written to the real filesystem, the
index is generated by the real ``vault feature index`` command, and every
assertion reads real CLI output or real on-disk state.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from pathlib import Path

    from vaultspec_core.tests.cli.workspace_factory import WorkspaceFactory

pytestmark = [pytest.mark.unit]

DATE = "2026-06-26"


def _write(path: Path, tags: list[str], related: list[str], extra_fm: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tag_lines = "".join(f"  - '{t}'\n" for t in tags)
    if related:
        rel_block = "related:\n" + "".join(f"  - '[[{r}]]'\n" for r in related)
    else:
        rel_block = "related: []\n"
    path.write_text(
        f"---\ntags:\n{tag_lines}date: '{DATE}'\nmodified: '{DATE}'\n"
        f"{extra_fm}{rel_block}---\n\n# Heading\n\nClean document body.\n",
        encoding="utf-8",
    )


def _seed_feature(root: Path, feature: str) -> None:
    """Write a connected, schema-valid feature that passes ``check all``."""
    vault = root / ".vault"
    _write(
        vault / "research" / f"{DATE}-{feature}-research.md",
        ["#research", f"#{feature}"],
        [],
    )
    _write(
        vault / "adr" / f"{DATE}-{feature}-adr.md",
        ["#adr", f"#{feature}"],
        [f"{DATE}-{feature}-research"],
    )
    _write(
        vault / "plan" / f"{DATE}-{feature}-plan.md",
        ["#plan", f"#{feature}"],
        [f"{DATE}-{feature}-adr", f"{DATE}-{feature}-research"],
        extra_fm="tier: L2\n",
    )
    _write(
        vault / "audit" / f"{DATE}-{feature}-perf-audit.md",
        ["#audit", f"#{feature}"],
        [f"{DATE}-{feature}-plan"],
    )
    exec_folder = vault / "exec" / f"{DATE}-{feature}"
    _write(
        exec_folder / f"{DATE}-{feature}-P01-S01.md",
        ["#exec", f"#{feature}"],
        [f"{DATE}-{feature}-plan"],
        extra_fm="step_id: 'S01'\n",
    )
    _write(
        exec_folder / f"{DATE}-{feature}-P01-summary.md",
        ["#exec", f"#{feature}"],
        [f"{DATE}-{feature}-plan"],
    )


def test_rename_cli_renames_and_check_all_clean(factory: WorkspaceFactory) -> None:
    factory.install("core")
    _seed_feature(factory.path, "widget-engine")
    assert (
        factory.run("vault", "feature", "index", "-f", "widget-engine").exit_code == 0
    )

    result = factory.run("vault", "feature", "rename", "widget-engine", "gadget-engine")

    assert result.exit_code == 0, result.output
    assert "Renamed" in result.output
    assert "widget-engine" in result.output
    assert "gadget-engine" in result.output

    # The new feature is materialised and the old one is gone on disk.
    vault = factory.path / ".vault"
    assert (vault / "adr" / f"{DATE}-gadget-engine-adr.md").is_file()
    assert not (vault / "adr" / f"{DATE}-widget-engine-adr.md").exists()

    check = factory.run("vault", "check", "all")
    assert check.exit_code == 0, check.output


def test_rename_cli_json_envelope(factory: WorkspaceFactory) -> None:
    factory.install("core")
    _seed_feature(factory.path, "widget-engine")
    factory.run("vault", "feature", "index", "-f", "widget-engine")

    result = factory.run(
        "vault", "feature", "rename", "widget-engine", "gadget-engine", "--json"
    )

    assert result.exit_code == 0, result.output
    envelope = json.loads(result.output)
    assert envelope["schema"] == "vaultspec.vault.feature.rename.v1"
    assert envelope["status"] == "updated"
    data = envelope["data"]
    assert data["old"] == "widget-engine"
    assert data["new"] == "gadget-engine"
    assert data["renamed_count"] >= 1


def test_rename_cli_collision_without_force_fails(factory: WorkspaceFactory) -> None:
    factory.install("core")
    _seed_feature(factory.path, "widget-engine")
    # A pre-existing target feature: rename without --force must refuse.
    _write(
        factory.path / ".vault" / "research" / f"{DATE}-gadget-engine-research.md",
        ["#research", "#gadget-engine"],
        [],
    )

    result = factory.run(
        "vault", "feature", "rename", "widget-engine", "gadget-engine", "--json"
    )

    assert result.exit_code != 0
    envelope = json.loads(result.output)
    assert envelope["status"] == "failed"
    assert "already has" in envelope["data"]["message"]

    # Nothing was mutated: the source feature's adr is still present.
    assert (factory.path / ".vault" / "adr" / f"{DATE}-widget-engine-adr.md").is_file()
